"""Standalone InvestScan workspace and sessions

Идентификатор ревизии: e6078027ba98
Предыдущая ревизия: 20d4e38a77b1
Дата создания: 2026-09-06 04:38:52.344405
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "e6078027ba98"
down_revision: Union[str, Sequence[str], None] = "20d4e38a77b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет изменения схемы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "is_buyers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "contact", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False
        ),
        sa.Column(
            "asset_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False
        ),
        sa.Column("districts", sa.JSON(), nullable=False),
        sa.Column("max_budget", sa.Integer(), nullable=False),
        sa.Column("min_area", sa.Float(), nullable=False),
        sa.Column("max_area", sa.Float(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "is_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "issuer", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "subject", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
    )
    op.create_table(
        "is_import_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("unchanged", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "is_objects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "asset_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False
        ),
        sa.Column(
            "district", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False
        ),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False
        ),
        sa.Column("area", sa.Float(), nullable=False),
        sa.Column(
            "land_use", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False
        ),
        sa.Column(
            "cadastral_number",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("asking_price", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "urgency_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("seller_deadline", sa.DateTime(), nullable=True),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("starred", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_is_objects_asset_type"), "is_objects", ["asset_type"], unique=False
    )
    op.create_index(
        op.f("ix_is_objects_cadastral_number"),
        "is_objects",
        ["cadastral_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_is_objects_district"), "is_objects", ["district"], unique=False
    )
    op.create_index(op.f("ix_is_objects_stage"), "is_objects", ["stage"], unique=False)
    op.create_table(
        "is_searches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "is_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["is_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_is_activity_object_id"), "is_activity", ["object_id"], unique=False
    )
    op.create_table(
        "is_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["is_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_id", "code"),
    )
    op.create_index(
        op.f("ix_is_checks_object_id"), "is_checks", ["object_id"], unique=False
    )
    op.create_table(
        "is_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("object_version", sa.Integer(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["is_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_is_evaluations_object_id"),
        "is_evaluations",
        ["object_id"],
        unique=False,
    )
    op.create_table(
        "is_sessions",
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column(
            "csrf_token", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["is_identities.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_is_sessions_identity_id"), "is_sessions", ["identity_id"], unique=False
    )
    op.create_table(
        "is_source_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False
        ),
        sa.Column(
            "external_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=1500), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["is_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id"),
    )
    op.create_index(
        op.f("ix_is_source_listings_object_id"),
        "is_source_listings",
        ["object_id"],
        unique=False,
    )
    op.create_table(
        "is_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False
        ),
        sa.Column(
            "assignee", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False
        ),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["is_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_is_tasks_object_id"), "is_tasks", ["object_id"], unique=False
    )
    op.create_table(
        "is_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["is_source_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["is_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_is_prices_object_id"), "is_prices", ["object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает изменения схемы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_is_prices_object_id"), table_name="is_prices")
    op.drop_table("is_prices")
    op.drop_index(op.f("ix_is_tasks_object_id"), table_name="is_tasks")
    op.drop_table("is_tasks")
    op.drop_index(
        op.f("ix_is_source_listings_object_id"), table_name="is_source_listings"
    )
    op.drop_table("is_source_listings")
    op.drop_index(op.f("ix_is_sessions_identity_id"), table_name="is_sessions")
    op.drop_table("is_sessions")
    op.drop_index(op.f("ix_is_evaluations_object_id"), table_name="is_evaluations")
    op.drop_table("is_evaluations")
    op.drop_index(op.f("ix_is_checks_object_id"), table_name="is_checks")
    op.drop_table("is_checks")
    op.drop_index(op.f("ix_is_activity_object_id"), table_name="is_activity")
    op.drop_table("is_activity")
    op.drop_table("is_searches")
    op.drop_index(op.f("ix_is_objects_stage"), table_name="is_objects")
    op.drop_index(op.f("ix_is_objects_district"), table_name="is_objects")
    op.drop_index(op.f("ix_is_objects_cadastral_number"), table_name="is_objects")
    op.drop_index(op.f("ix_is_objects_asset_type"), table_name="is_objects")
    op.drop_table("is_objects")
    op.drop_table("is_import_runs")
    op.drop_table("is_identities")
    op.drop_table("is_buyers")
    # ### end Alembic commands ###
